### ISSUE TITLE
cannot install NameError: uninitialized constant Redmine::Utils

### ISSUE THREAD

**Issue by richman1000000** [tainewoo/redmine_ldap_sync#9]
Hi I'm trying to install this plugin in server and getting error 

rake aborted!
NameError: uninitialized constant Redmine::Utils
/opt/redmine-4.1.1/lib/redmine/scm/adapters/abstract_adapter.rb:28:in `<class:AbstractAdapter>'
/opt/redmine-4.1.1/lib/redmine/scm/adapters/abstract_adapter.rb:27:in `<module:Adapters>'
/opt/redmine-4.1.1/lib/redmine/scm/adapters/abstract_adapter.rb:25:in `<module:Scm>'
/opt/redmine-4.1.1/lib/redmine/scm/adapters/abstract_adapter.rb:24:in `<module:Redmine>'
/opt/redmine-4.1.1/lib/redmine/scm/adapters/abstract_adapter.rb:23:in `<top (required)>'
/opt/redmine-4.1.1/lib/redmine/scm/adapters/subversion_adapter.rb:20:in `require'
/opt/redmine-4.1.1/lib/redmine/scm/adapters/subversion_adapter.rb:20:in `<top (required)>'
/opt/redmine-4.1.1/lib/redmine/version.rb:3:in `require'
/opt/redmine-4.1.1/lib/redmine/version.rb:3:in `<top (required)>'
/opt/redmine-4.1.1/plugins/redmine_ldap_sync/lib/tasks/testing.rake:27:in `require'
/opt/redmine-4.1.1/plugins/redmine_ldap_sync/lib/tasks/testing.rake:27:in `block (4 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:ldap_sync:test
(See full trace by running task with --trace)

**Comment by richman1000000** [comment]
turns out this command will not work.
rake redmine:plugins:ldap_sync:test
